name: english_time_travel
description: "English Time Travel - Glossario gamificado da historia americana."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0-254.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A0B2E"
  adaptive_icon_foreground: "assets/icon/icon.png"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 256
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#1A0B2E"
    theme_color: "#9B6BFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
