// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm4pTImMVytwFt-kLiQt1MIwJWI8kM0rg',
    appId: '1:395588868163:web:fcf6671bc30658e3429cf6',
    messagingSenderId: '395588868163',
    projectId: 'english-time-travel-app',
    authDomain: 'english-time-travel-app.firebaseapp.com',
    storageBucket: 'english-time-travel-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKRAaLHxEnIIGWdVu1P_ev7AsB2JUc25E',
    appId: '1:395588868163:android:0b6ded285d6803e1429cf6',
    messagingSenderId: '395588868163',
    projectId: 'english-time-travel-app',
    storageBucket: 'english-time-travel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwl4SYCYjnYZaFb9vYtnjQdZa83PFSrcQ',
    appId: '1:395588868163:ios:c0fcf709b271db8f429cf6',
    messagingSenderId: '395588868163',
    projectId: 'english-time-travel-app',
    storageBucket: 'english-time-travel-app.firebasestorage.app',
    iosBundleId: 'com.chronokairo.englishTimeTravel',
  );
}
